// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDXKN-690h6FEbzhsx3DhERAVVuyuVwY',
    appId: '1:340431038693:web:97081d1905cde66daecc0c',
    messagingSenderId: '340431038693',
    projectId: 'flutter-fire-try-6831a',
    authDomain: 'flutter-fire-try-6831a.firebaseapp.com',
    storageBucket: 'flutter-fire-try-6831a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBubPBHLDvsMKtoZEZF3rFHKmDuC1rDtf0',
    appId: '1:340431038693:android:7a1e9f25d09ba55eaecc0c',
    messagingSenderId: '340431038693',
    projectId: 'flutter-fire-try-6831a',
    storageBucket: 'flutter-fire-try-6831a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByme3K6CDKa-H5n6RDxtNl_uC4I4EkxZU',
    appId: '1:340431038693:ios:e37ea8169455a00daecc0c',
    messagingSenderId: '340431038693',
    projectId: 'flutter-fire-try-6831a',
    storageBucket: 'flutter-fire-try-6831a.appspot.com',
    iosClientId: '340431038693-48f1g4fbl257vjhouphtnsj46d950j9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.moencakApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByme3K6CDKa-H5n6RDxtNl_uC4I4EkxZU',
    appId: '1:340431038693:ios:e37ea8169455a00daecc0c',
    messagingSenderId: '340431038693',
    projectId: 'flutter-fire-try-6831a',
    storageBucket: 'flutter-fire-try-6831a.appspot.com',
    iosClientId: '340431038693-48f1g4fbl257vjhouphtnsj46d950j9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.moencakApps',
  );
}
