// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUAVLSHVLl1Bg8kWPzBr2g1JEZpsIerw',
    appId: '1:443699200036:web:82773d25eaf25b681058b1',
    messagingSenderId: '443699200036',
    projectId: 'e-prau',
    authDomain: 'e-prau.firebaseapp.com',
    storageBucket: 'e-prau.appspot.com',
    measurementId: 'G-T8G5RSXPET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1DXAtI3PsDHud4NvAg0PTiGUlYoDpa0',
    appId: '1:443699200036:android:e60cc317e01d2b6e1058b1',
    messagingSenderId: '443699200036',
    projectId: 'e-prau',
    storageBucket: 'e-prau.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkbiV3tMqjw7o5Ha-y51U9QeuTlePXuXo',
    appId: '1:443699200036:ios:c7ed17d18ad803331058b1',
    messagingSenderId: '443699200036',
    projectId: 'e-prau',
    storageBucket: 'e-prau.appspot.com',
    iosBundleId: 'com.example.moencakApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkbiV3tMqjw7o5Ha-y51U9QeuTlePXuXo',
    appId: '1:443699200036:ios:c7ed17d18ad803331058b1',
    messagingSenderId: '443699200036',
    projectId: 'e-prau',
    storageBucket: 'e-prau.appspot.com',
    iosBundleId: 'com.example.moencakApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoUAVLSHVLl1Bg8kWPzBr2g1JEZpsIerw',
    appId: '1:443699200036:web:f292305c5b3ea5c21058b1',
    messagingSenderId: '443699200036',
    projectId: 'e-prau',
    authDomain: 'e-prau.firebaseapp.com',
    storageBucket: 'e-prau.appspot.com',
    measurementId: 'G-YSMK7ZG21N',
  );

}
